import './globals.css';
import { latin } from './fonts';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next Eth',
  keywords: 'nextjs eth web3',
  description: 'Generated by create next app'
};

function CustomLinks() {
  const CDN = 'http://localhost:3000';
  return (
    <>
      <link rel='preload' href={CDN + '/fonts/ERASB.ttf'} as='font' type='font/ttf' crossOrigin='anonymous' />
    </>
  );
}

function CustomStyle() {
  const CDN = 'http://localhost:3000';
  return (
    <style>{`
    @font-face {
      font-family: ERASB;
      font-style: normal;
      font-weight: 400;
      font-display: swap;
      src: url(${CDN + '/fonts/ERASB.ttf'});
    }
    .erasb {
      font-family: ERASB;
    }`}</style>
  );
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <CustomLinks />
        <CustomStyle />
      </head>
      <body className={latin.className}>{children}</body>
    </html>
  );
}

